version: '3.8'

services:
  database:
    image: postgres
    container_name: database_safra
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=safra
      - POSTGRES_DB=apiSafra
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: apiSafra
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
    